[[TOPCOM]]
arch = "aarch64"
git-tree-sha1 = "113d9e316f8e5c77a87460a806035945062c8bcb"
os = "macos"

    [[TOPCOM.download]]
    sha256 = "5341d174086cc89d5dea55fd371ae18ba3ef67ac05a7553786cd02da2f4765f3"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.aarch64-apple-darwin.tar.gz"
[[TOPCOM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd6739edfca014108f866f108d0b6ec89939be2a"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "edeca39dfc948d0482b8c7f230bfe95e3600fa8eda9c066597e839c2215c14c4"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.aarch64-linux-gnu-cxx03.tar.gz"
[[TOPCOM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cecb971e432b80305768a810c9d295d92fca04d"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "6dd883954a662d0aedc59cb10bc5f06cb35f14b8e98ed0da5dc0d935e6d10ded"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.aarch64-linux-gnu-cxx11.tar.gz"
[[TOPCOM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "501984a8bfc35685ac2e7851f419eb32dab6025b"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "d42611707f85bf2552aa10393c76e033f0af418052d6a2ceb232324724885f11"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.aarch64-linux-musl-cxx03.tar.gz"
[[TOPCOM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c734824811285b93bbe4bc9f857dd9aca0e32ce9"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "c23ea44a08c43f96bd3cf84cb8fe3efd8828513f7c27ea7b82e22cbb52d246fd"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.aarch64-linux-musl-cxx11.tar.gz"
[[TOPCOM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3d07bdda59e2a91caa1a453b9ebc8383cbe95a3"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "80a7c85acad59b3132b5993cdc3feb4b150a90c369d54273a015cd6c5e411d10"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[TOPCOM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c065b80f53eb84aa4bb5cbf1725552612d2b1c4"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "24731f9cdbfb3df38c6912967e566d9b48ae2eeb6291ba6663f101d3d6ccd7de"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TOPCOM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47a91eaf6a092ffc6056f1ebb3ebc757ca59687a"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "318448a9638efe928cf1b4bde5fd8389b4909d33195dbc10b16293d8d37cd00b"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv6l-linux-musleabihf-cxx03.tar.gz"
[[TOPCOM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "197c7d65d8a0780bcd36b28d91c327c1012cd51f"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "105d5d939c7e825be10beb450d2526662f16aa05119985636ea7adf3e10c95a5"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[TOPCOM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c3c3f44a37e22a35455c311a912d70a56888b23"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "1ec6f6d434deb9393ea470a4e8fddad880f94b5bb2eb88959c7a5084d924fced"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[TOPCOM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f8127201103a081da8858fadce18dbb0cf48686"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "ab41babddae2ddbf63f415c06a969b67c6e0c9de24d5c2cd3168d6754af27b61"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TOPCOM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2568599879ec1d251bc63fb863df139d7769a258"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "0d970c94738b7721a2856a384e7266efdec8694b1bd43534664b95eb551f01d1"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv7l-linux-musleabihf-cxx03.tar.gz"
[[TOPCOM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15ff2507ca84c3f59749750c1c7c1661457a3955"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "21f274dd3d99d0b94e7d27ec6e781907b416ca1a9e7fc8d54da545c78d8dd372"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e8f4d19493f326f13627a9ae7a72d5a98caf87b"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "34f391b29ccbf2102ba99ad4eea23d82e0dad0c397fbe403e938fb50868f38e0"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-linux-gnu-cxx03.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19f487ee98c59111dcb11d5a30f69f84a9f36b14"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "b7f2bffaee2a7af8973ebb0fcd65f113df9b3f3885abee5ffc159928929a5686"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-linux-gnu-cxx11.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b659695ce0e7d8740cecb6d616636f539734d7ed"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "d80e48f21a6926d0a828490240231e8b3323d70c448077cc83d3f881e8b22f1b"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-linux-musl-cxx03.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7167f4dadfb3d5d7caa8eb0254308321a28d9472"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "1fae0f7c422b961ca7adb586a27c50509d3da4a668fde3b42342e54b494b0956"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-linux-musl-cxx11.tar.gz"
[[TOPCOM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faab8c3e7f4c2d98dfd8e12b72b237958913a57e"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "bd726c1018df0aeae6c5397ba7251a07b524940cd6f42f871e92cc5824997bb3"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.powerpc64le-linux-gnu-cxx03.tar.gz"
[[TOPCOM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f7b7928c390967e42356ded28511a505dae2025"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "020dcc243a2fcaa5520e1a548470fab12ac6f80eced94ea47d752fc28904a8f2"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TOPCOM]]
arch = "x86_64"
git-tree-sha1 = "08f72287432902b08e8e35fe70a4a1c780eae81c"
os = "macos"

    [[TOPCOM.download]]
    sha256 = "188ac37914f0373e2493dec7ae0a0cd9b2069271e9c76ad21b5a9f61ecd2626f"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-apple-darwin.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e1e6ab19af54784ae72916d3d5e30546898e854"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "9798f1f30939a7c1af7b9550850bdc6ce6ea542a2da1e45171b47a055ab2d421"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-linux-gnu-cxx03.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f1717d808f99e7f59eb6232557f070f5cd05d7d"
libc = "glibc"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "279a072fff168bb8c9161cf0fbf9cb60f86c85ea99edfd2f5fd37c69233763e9"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-linux-gnu-cxx11.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "402ce9575ee8c21ac2620c488ea4869656b7d913"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "0967d3bb3ade6eef95403482f254fff2013fb92b09ce27a1d8f38b3e6b747da2"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-linux-musl-cxx03.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d883100042fbd69f3c331a0cf09d012fec6cd040"
libc = "musl"
os = "linux"

    [[TOPCOM.download]]
    sha256 = "82cfd6fce2e46827138069736df67d90fbc4863fd86292f386327266f7700865"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-linux-musl-cxx11.tar.gz"
[[TOPCOM]]
arch = "x86_64"
git-tree-sha1 = "a58f87ff6b71ed4a28306ce2417ff38ed80f689c"
os = "freebsd"

    [[TOPCOM.download]]
    sha256 = "3cfddf6eb79e61906d24079a5c197f76eeca75db8dff63e3879370f45cbaa2ae"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-unknown-freebsd.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1baf8b0baeef6ac3838d2f8610755f8363db4555"
os = "windows"

    [[TOPCOM.download]]
    sha256 = "8882d981be45b0965301fb4c1f195ef839314ca06f170bc3f3a4b42a46e0052e"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-w64-mingw32-cxx03.tar.gz"
[[TOPCOM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c457a532e635e426e7d48240591370dbb83afda"
os = "windows"

    [[TOPCOM.download]]
    sha256 = "a35ad64ec318b752f6b21880a41eb98b9bbd608ace7962556c9575f116bcc151"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.i686-w64-mingw32-cxx11.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc0fa77617665e077171c28f3513f6d3e65f5bef"
os = "windows"

    [[TOPCOM.download]]
    sha256 = "127b66fb672bbbe11a466b2653d752aa06bb113caee66c8352edf49c282ed813"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-w64-mingw32-cxx03.tar.gz"
[[TOPCOM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cdf286ab94e11c923ed4bde177d4f77d11a48fe"
os = "windows"

    [[TOPCOM.download]]
    sha256 = "bb897481556a7e9130cca4a94b6211311fb6f7d401a2a80df6d0b257666b9696"
    url = "https://github.com/JuliaBinaryWrappers/TOPCOM_jll.jl/releases/download/TOPCOM-v0.17.8+0/TOPCOM.v0.17.8.x86_64-w64-mingw32-cxx11.tar.gz"
