# Autogenerated wrapper script for TOPCOM_jll for x86_64-w64-mingw32-cxx03
export chiro2allfinetriangs, chiro2alltriangs, chiro2circuits, chiro2cocircuits, chiro2dual, chiro2finetriang, chiro2finetriangs, chiro2mintriang, chiro2nallfinetriangs, chiro2nalltriangs, chiro2nfinetriangs, chiro2ntriangs, chiro2placingtriang, chiro2triangs, cocircuits2facets, points2allfinetriangs, points2alltriangs, points2chiro, points2facets, points2finetriang, points2finetriangs, points2flips, points2nallfinetriangs, points2nalltriangs, points2nfinetriangs, points2nflips, points2ntriangs, points2placingtriang, points2triangs, points2volume, santos_22_triang, santos_dim4_triang, santos_triang

using GMP_jll
using cddlib_jll
JLLWrappers.@generate_wrapper_header("TOPCOM")
JLLWrappers.@declare_executable_product(chiro2allfinetriangs)
JLLWrappers.@declare_executable_product(chiro2alltriangs)
JLLWrappers.@declare_executable_product(chiro2circuits)
JLLWrappers.@declare_executable_product(chiro2cocircuits)
JLLWrappers.@declare_executable_product(chiro2dual)
JLLWrappers.@declare_executable_product(chiro2finetriang)
JLLWrappers.@declare_executable_product(chiro2finetriangs)
JLLWrappers.@declare_executable_product(chiro2mintriang)
JLLWrappers.@declare_executable_product(chiro2nallfinetriangs)
JLLWrappers.@declare_executable_product(chiro2nalltriangs)
JLLWrappers.@declare_executable_product(chiro2nfinetriangs)
JLLWrappers.@declare_executable_product(chiro2ntriangs)
JLLWrappers.@declare_executable_product(chiro2placingtriang)
JLLWrappers.@declare_executable_product(chiro2triangs)
JLLWrappers.@declare_executable_product(cocircuits2facets)
JLLWrappers.@declare_executable_product(points2allfinetriangs)
JLLWrappers.@declare_executable_product(points2alltriangs)
JLLWrappers.@declare_executable_product(points2chiro)
JLLWrappers.@declare_executable_product(points2facets)
JLLWrappers.@declare_executable_product(points2finetriang)
JLLWrappers.@declare_executable_product(points2finetriangs)
JLLWrappers.@declare_executable_product(points2flips)
JLLWrappers.@declare_executable_product(points2nallfinetriangs)
JLLWrappers.@declare_executable_product(points2nalltriangs)
JLLWrappers.@declare_executable_product(points2nfinetriangs)
JLLWrappers.@declare_executable_product(points2nflips)
JLLWrappers.@declare_executable_product(points2ntriangs)
JLLWrappers.@declare_executable_product(points2placingtriang)
JLLWrappers.@declare_executable_product(points2triangs)
JLLWrappers.@declare_executable_product(points2volume)
JLLWrappers.@declare_executable_product(santos_22_triang)
JLLWrappers.@declare_executable_product(santos_dim4_triang)
JLLWrappers.@declare_executable_product(santos_triang)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, cddlib_jll)
    JLLWrappers.@init_executable_product(
        chiro2allfinetriangs,
        "bin\\chiro2allfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2alltriangs,
        "bin\\chiro2alltriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2circuits,
        "bin\\chiro2circuits.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2cocircuits,
        "bin\\chiro2cocircuits.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2dual,
        "bin\\chiro2dual.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2finetriang,
        "bin\\chiro2finetriang.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2finetriangs,
        "bin\\chiro2finetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2mintriang,
        "bin\\chiro2mintriang.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2nallfinetriangs,
        "bin\\chiro2nallfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2nalltriangs,
        "bin\\chiro2nalltriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2nfinetriangs,
        "bin\\chiro2nfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2ntriangs,
        "bin\\chiro2ntriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2placingtriang,
        "bin\\chiro2placingtriang.exe",
    )

    JLLWrappers.@init_executable_product(
        chiro2triangs,
        "bin\\chiro2triangs.exe",
    )

    JLLWrappers.@init_executable_product(
        cocircuits2facets,
        "bin\\cocircuits2facets.exe",
    )

    JLLWrappers.@init_executable_product(
        points2allfinetriangs,
        "bin\\points2allfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2alltriangs,
        "bin\\points2alltriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2chiro,
        "bin\\points2chiro.exe",
    )

    JLLWrappers.@init_executable_product(
        points2facets,
        "bin\\points2facets.exe",
    )

    JLLWrappers.@init_executable_product(
        points2finetriang,
        "bin\\points2finetriang.exe",
    )

    JLLWrappers.@init_executable_product(
        points2finetriangs,
        "bin\\points2finetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2flips,
        "bin\\points2flips.exe",
    )

    JLLWrappers.@init_executable_product(
        points2nallfinetriangs,
        "bin\\points2nallfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2nalltriangs,
        "bin\\points2nalltriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2nfinetriangs,
        "bin\\points2nfinetriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2nflips,
        "bin\\points2nflips.exe",
    )

    JLLWrappers.@init_executable_product(
        points2ntriangs,
        "bin\\points2ntriangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2placingtriang,
        "bin\\points2placingtriang.exe",
    )

    JLLWrappers.@init_executable_product(
        points2triangs,
        "bin\\points2triangs.exe",
    )

    JLLWrappers.@init_executable_product(
        points2volume,
        "bin\\points2volume.exe",
    )

    JLLWrappers.@init_executable_product(
        santos_22_triang,
        "bin\\santos_22_triang.exe",
    )

    JLLWrappers.@init_executable_product(
        santos_dim4_triang,
        "bin\\santos_dim4_triang.exe",
    )

    JLLWrappers.@init_executable_product(
        santos_triang,
        "bin\\santos_triang.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
